# Site settings
title: Steboh Lars Kemper und Kim Steverding Gbr
email1: kim@steboh.com
email2: lars@steboh.com
description: > # this means to ignore newlines until "baseurl:"
  Unkonventionell. Disruptiv. Vision√§r.<br>
  Wir sind die Zukunft.
  
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://steboh.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
